### ISSUE TITLE
Jetson Level Shifter

### ISSUE THREAD

**Issue by triggerfinger-debug** [kmwebnet/simplecodec3#1]
HI,
would you please share your Jetson Level Shifter Schematic? The picture on your blog I can't read.

**Comment by cyberomusubi** [comment]
Here you are.
[simplecodec-levelshifter.pdf](https://github.com/kmwebnet/simplecodec3/files/10974348/simplecodec-levelshifter.pdf)

**Comment by triggerfinger-debug** [comment]
Thank you :)
